
services:
  # UI
  ui:
    build:
      context: .
      dockerfile: Docker/UI/Dockerfile
    image: inventory/ui
    ports:
      - '5000:3000'
  # Backend
  backend:
    build:
      context: .
      dockerfile: Docker/Backend/Dockerfile
    image: inventory/backend
    depends_on:
      - "database"
    ports:
      - '5001:5001'
  # Postgres DB
  database:
    image: "postgres"
    ports:
      - '5432:5432'
    expose:
      - '5432'
    env_file:
      - Docker/database.env
    volumes:
      - database-data:/var/lib/postgresql/data-inventory/
  # Restfox
  restfox:
    image: "flawiddsouza/restfox:0.17.0"
    ports:
      - '4004:4004'
    expose:
      - '4004'
    volumes:
      - restfox-data:/var/lib/postgresql/data-inventory/
volumes:
  database-data:
  restfox-data: