# stage1 - build react app first 
FROM node:latest as build
ENV PATH /app/node_modules/.bin:$PATH
COPY ./ui/package.json /app/
COPY ./ui/yarn.lock /app/
RUN yarn --cwd /app 
COPY ./ui /app
RUN yarn --cwd /app build 

# stage 2 - build the final image and copy the react build files
FROM nginx:latest
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./Docker/UI/nginx.conf /etc/nginx/conf.d
CMD ["nginx", "-g", "daemon off;"]